import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { randomBytes } from "crypto";
import { PurchaseOrderStatus } from "@ixoris/database";
import { PrismaService } from "../../prisma/prisma.service";
import { ApprovalsService } from "../documents/approvals.service";
import { toNumber } from "../pos/pos.mappers";
import { CreatePurchaseOrderDto } from "./dto/create-purchase-order.dto";

const poInclude = { lines: { include: { product: true } }, supplier: true, warehouse: true } as const;

@Injectable()
export class PurchaseOrdersService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly approvals: ApprovalsService,
  ) {}

  async create(companyId: string, createdById: string | undefined, dto: CreatePurchaseOrderDto, autoGenerated = false) {
    const lines = dto.lines.map((l) => {
      const ht = round2(l.quantityOrdered * l.unitPrice);
      const tva = round2(ht * (l.tvaRate / 100));
      return { ...l, ht, tva, total: round2(ht + tva) };
    });
    const totalHT = round2(lines.reduce((s, l) => s + l.ht, 0));
    const totalTVA = round2(lines.reduce((s, l) => s + l.tva, 0));
    const totalTTC = round2(totalHT + totalTVA);

    return this.prisma.purchaseOrder.create({
      data: {
        companyId,
        supplierId: dto.supplierId,
        warehouseId: dto.warehouseId,
        number: generatePoNumber(),
        expectedDate: dto.expectedDate ? new Date(dto.expectedDate) : undefined,
        totalHT,
        totalTVA,
        totalTTC,
        autoGenerated,
        createdById,
        notes: dto.notes,
        lines: {
          create: lines.map((l) => ({
            productId: l.productId,
            quantityOrdered: l.quantityOrdered,
            unitPrice: l.unitPrice,
            tvaRate: l.tvaRate,
            total: l.total,
          })),
        },
      },
      include: poInclude,
    });
  }

  list(companyId: string, status?: PurchaseOrderStatus) {
    return this.prisma.purchaseOrder.findMany({
      where: { companyId, status },
      include: poInclude,
      orderBy: { orderDate: "desc" },
      take: 200,
    });
  }

  async findOne(companyId: string, id: string) {
    const po = await this.prisma.purchaseOrder.findFirst({ where: { id, companyId }, include: poInclude });
    if (!po) throw new NotFoundException(`Purchase order ${id} not found`);
    return po;
  }

  /** Above an ApprovalRule threshold, sending is held until an ApprovalRequest is APPROVED instead of going straight to SENT. */
  async send(companyId: string, id: string, userId: string) {
    const po = await this.findOne(companyId, id);
    if (po.status !== "DRAFT") throw new BadRequestException(`Purchase order ${po.number} is not a draft`);

    const pendingApproval = await this.prisma.approvalRequest.findFirst({ where: { companyId, type: "PURCHASE_ORDER", targetId: id, status: "PENDING" } });
    if (pendingApproval) throw new BadRequestException(`Purchase order ${po.number} is awaiting approval`);

    const rejected = await this.prisma.approvalRequest.findFirst({ where: { companyId, type: "PURCHASE_ORDER", targetId: id, status: "REJECTED" } });
    if (rejected) throw new BadRequestException(`Purchase order ${po.number} was rejected and cannot be sent`);

    const approved = await this.prisma.approvalRequest.findFirst({ where: { companyId, type: "PURCHASE_ORDER", targetId: id, status: "APPROVED" } });
    if (!approved) {
      const request = await this.approvals.requestIfNeeded(companyId, "PURCHASE_ORDER", id, toNumber(po.totalTTC), userId);
      if (request) return { ...po, approvalRequest: request };
    }

    return this.prisma.purchaseOrder.update({ where: { id }, data: { status: "SENT" }, include: poInclude });
  }

  async cancel(companyId: string, id: string) {
    const po = await this.findOne(companyId, id);
    if (po.status === "RECEIVED" || po.status === "CANCELLED") {
      throw new BadRequestException(`Purchase order ${po.number} can no longer be cancelled`);
    }
    return this.prisma.purchaseOrder.update({ where: { id }, data: { status: "CANCELLED" }, include: poInclude });
  }
}

function generatePoNumber(): string {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  return `PO-${date}-${randomBytes(3).toString("hex").toUpperCase()}`;
}

function round2(value: number): number {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}
